spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    gcp:
      storage:
        credentials:
          location: ${GCP_STORAGE_LOCATION}
        project-id: ${GCP_STORAGE_PROJECT_ID}
        bucket: ${GCP_STORAGE_BUCKET}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
